apiVersion: v1
kind: Service
metadata:
  name: chat-backend-service
  namespace: default
  labels:
    app: chat-backend
spec:
  type: ClusterIP
  selector:
    app: chat-backend
  ports:
    - protocol: TCP
      port: 19092
      targetPort: 19092 