name: CI/CD Deploy Chat Backend to Kubernetes

on:
  push:
    branches: [ main, sichan ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.CHAT_DOCKER_IMAGE }}
      CHAT_DB_URL: ${{ secrets.CHAT_DB_URL }}
      CHAT_DB_USER: ${{ secrets.CHAT_DB_USER }}
      CHAT_DB_PASSWORD: ${{ secrets.CHAT_DB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          build-args: |
            PROFILE_ACTIVE=prod

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Create or update chat-backend-secret
        run: |
          kubectl create secret generic chat-backend-secret \
            --from-literal=CHAT_DB_URL="${{ secrets.CHAT_DB_URL }}" \
            --from-literal=CHAT_DB_USER="${{ secrets.CHAT_DB_USER }}" \
            --from-literal=CHAT_DB_PASSWORD="${{ secrets.CHAT_DB_PASSWORD }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Replace image tag and apply deployment
        run: |
          sed "s#__DOCKER_IMAGE__#${{ secrets.CHAT_DOCKER_IMAGE }}#g" k8s/chat_deployment.yaml | \
          sed "s#__TAG__#${{ github.sha }}#g" > k8s/chat_deployment.generated.yaml

          kubectl apply -f k8s/chat_deployment.generated.yaml

      - name: apply service
        run: |
          kubectl apply -f k8s/chat_service.yaml 